import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    mainSidebar: [
        "index",
        {
            type: "category",
            label: "Quickstart",
            items: [
                {
                    type: "doc",
                    id: "quickstart/index",
                    label: "Installation",
                },
                {
                    type: "doc",
                    id: "quickstart/writing-test",
                    label: "Writing a test",
                },
                {
                    type: "doc",
                    id: "quickstart/launch-debugging",
                    label: "Launch and debugging",
                },
              ],
        },
        {
            type: "category",
            label: "Commands",
            items: [
                {
                    type: "category",
                    label: "browser",
                    items: [{ type: "autogenerated", dirName: "commands/browser" }],
                },
                {
                    type: "category",
                    label: "element",
                    items: [{ type: "autogenerated", dirName: "commands/element" }],
                },
                {
                    type: "category",
                    label: "expect",
                    items: [{ type: "autogenerated", dirName: "commands/expect" }],
                    link: { type: "doc", id: "commands/expect/overview" },
                },
                {
                    type: "category",
                    label: "mock",
                    items: [{ type: "autogenerated", dirName: "commands/mock" }],
                },
            ],
            link: { type: "doc", id: "commands/overview" },
        },
        {
            type: "category",
            label: "Key concepts",
            items: [{ type: "autogenerated", dirName: "key-concepts" }],
        },
        {
            type: "category",
            label: "Config",
            items: [{ type: "autogenerated", dirName: "config" }],
            link: { type: "doc", id: "config/main" },
        },
        {
            type: "category",
            label: "Types of testing",
            items: [{ type: "autogenerated", dirName: "testing-types" }],
        },
        {
            type: "category",
            label: "Migrations",
            items: [{ type: "autogenerated", dirName: "migrations" }],
        },
        {
            type: "category",
            label: "Plugins",
            items: [{ type: "autogenerated", dirName: "plugins" }],
        },
        {
            type: "category",
            label: "Reference",
            items: [{ type: "autogenerated", dirName: "reference" }],
        },
        {
            type: "category",
            label: "Comparison",
            items: [{ type: "autogenerated", dirName: "comparison" }],
            link: { type: "doc", id: "comparison/compare-with-playwright" },
        },
    ],
    ui: [
        { type: "autogenerated", dirName: "html-reporter" },
        {
            type: "category",
            label: "API",
            link: { type: "doc", id: "html-reporter/html-reporter-api" },
            items: [
                { type: "doc", id: "html-reporter/html-reporter-api" },
                { type: "doc", id: "html-reporter/html-reporter-events" },
                { type: "doc", id: "html-reporter/html-reporter-plugins-api" },
            ],
        },
    ],
};

export default sidebars;