import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    mainSidebar: [
        "index",
        {
            type: "category",
            label: "Getting Started",
            items: [{ type: "autogenerated", dirName: "quickstart" }],
        },
        {
            type: "category",
            label: "Commands",
            items: [
                {
                    type: "category",
                    label: "browser",
                    items: [{ type: "autogenerated", dirName: "commands/browser" }],
                },
                {
                    type: "category",
                    label: "element",
                    items: [{ type: "autogenerated", dirName: "commands/element" }],
                },
                {
                    type: "category",
                    label: "expect",
                    items: [{ type: "autogenerated", dirName: "commands/expect" }],
                    link: { type: "doc", id: "commands/expect/overview" },
                },
                {
                    type: "category",
                    label: "mock",
                    items: [{ type: "autogenerated", dirName: "commands/mock" }],
                },
            ],
            link: { type: "doc", id: "commands/overview" },
        },
        {
            type: "category",
            label: "Guides",
            items: [{ type: "autogenerated", dirName: "basic-guides" }],
        },
        {
            type: "category",
            label: "Advanced Guides",
            items: [{ type: "autogenerated", dirName: "guides" }],
        },
        {
            type: "doc",
            id: "testplane-mcp",
            label: "Testplane MCP",
        },
        {
            type: "category",
            label: "Migrations",
            items: [{ type: "autogenerated", dirName: "migrations" }],
        },
        {
            type: "category",
            label: "Plugins",
            items: [{ type: "autogenerated", dirName: "plugins" }],
        },
        {
            type: "category",
            label: "Сomparison",
            items: [{ type: "autogenerated", dirName: "comparison" }],
            link: { type: "doc", id: "comparison/compare-with-playwright" },
        },
    ],
    ui: [
        { type: "autogenerated", dirName: "html-reporter" },
        {
            type: "category",
            label: "API",
            link: { type: "doc", id: "html-reporter/html-reporter-api" },
            items: [
                { type: "doc", id: "html-reporter/html-reporter-api" },
                { type: "doc", id: "html-reporter/html-reporter-events" },
                { type: "doc", id: "html-reporter/html-reporter-plugins-api" },
            ],
        },
    ],
    api: [
        { type: "link", href: "/docs/v8/commands/overview", label: "Testplane Commands" },
        { type: "autogenerated", dirName: "reference" },
    ],
};

export default sidebars;
