import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    mainSidebar: [
        "index",
        {
            type: "doc",
            id: "quickstart/index",
            label: "Quickstart",
        },
        {
            type: "doc",
            id: "command-line/index",
            label: "CLI",
        },
        {
            type: "category",
            label: "Commands",
            items: [
                {
                    type: "category",
                    label: "browser",
                    items: [{ type: "autogenerated", dirName: "commands/browser" }],
                },
                {
                    type: "category",
                    label: "element",
                    items: [{ type: "autogenerated", dirName: "commands/element" }],
                },
                {
                    type: "category",
                    label: "expect",
                    items: [{ type: "autogenerated", dirName: "commands/expect" }],
                    link: { type: "doc", id: "commands/expect/overview" },
                },
                {
                    type: "category",
                    label: "mock",
                    items: [{ type: "autogenerated", dirName: "commands/mock" }],
                },
            ],
            link: { type: "doc", id: "commands/overview" },
        },
        {
            type: "category",
            label: "Config",
            items: [{ type: "autogenerated", dirName: "config" }],
            link: { type: "doc", id: "config/main" },
        },
        {
            type: "category",
            label: "Visual testing",
            items: [{ type: "autogenerated", dirName: "visual-testing" }],
            link: { type: "doc", id: "visual-testing/visual-testing-intro" },
        },
        {
            type: "category",
            label: "Guides",
            items: [{ type: "autogenerated", dirName: "guides" }],
        },
        {
            type: "category",
            label: "HTML Reporter",
            items: [{ type: "autogenerated", dirName: "html-reporter" }],
            link: { type: "doc", id: "html-reporter/html-reporter-setup" },
        },
        {
            type: "category",
            label: "Migrations",
            items: [{ type: "autogenerated", dirName: "migrations" }],
        },
        {
            type: "category",
            label: "Plugins",
            items: [{ type: "autogenerated", dirName: "plugins" }],
        },
        {
            type: "category",
            label: "Reference",
            items: [{ type: "autogenerated", dirName: "reference" }],
        },
    ],
};

export default sidebars;
