# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm test

    deploy-static:
        runs-on: ubuntu-latest
        environment: CI

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build-storybook
            - run: npm run build
              env:
                  DOCUSAURUS_URL: https://${{ secrets.AWS_S3_BUCKET }}.website.yandexcloud.net
                  DOCUSAURUS_BASE_URL: testplane-docs/website-static/${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}/
            - name: Upload storybook static
              uses: jakejarvis/s3-sync-action@v0.5.1
              with:
                  args: --acl public-read --follow-symlinks
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_S3_ENDPOINT: https://s3.yandexcloud.net/
                  SOURCE_DIR: "storybook-static"
                  DEST_DIR: "testplane-docs/storybook-static/${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}/"
            - name: Upload website static
              uses: jakejarvis/s3-sync-action@v0.5.1
              with:
                  args: --acl public-read --follow-symlinks
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_S3_ENDPOINT: https://s3.yandexcloud.net/
                  SOURCE_DIR: "build"
                  DEST_DIR: "testplane-docs/website-static/${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}/"

            - name: Comment PR with links to deployed static on success
              if: ${{ success() }}
              uses: thollander/actions-comment-pull-request@v2
              with:
                  message: |
                      ### :white_check_mark: Successfully deployed static

                      - [Docs website](https://${{ secrets.AWS_S3_BUCKET }}.website.yandexcloud.net/testplane-docs/website-static/${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}/)
                      - [Storybook](https://${{ secrets.AWS_S3_BUCKET }}.website.yandexcloud.net/testplane-docs/storybook-static/${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}/)
                  comment_tag: deployment_status

            - name: Comment PR that static wasn't deployed on failure
              if: ${{ failure() }}
              uses: thollander/actions-comment-pull-request@v2
              with:
                  message: |
                      ### :x: Failed to deploy static

                      Please check the workflow logs for details.
                  comment_tag: deployment_status
